name: pushCI

on:
  push:
    branches: master
    tags: 'v*'

jobs:
  images:
      name: Build and notarize Docker Images
      runs-on: ubuntu-latest
      env:
        JOB_NAME: ${{ github.job }}
        JOB_ID: ${{ github.run_id }}
        DOCKER_IMAGE_IMMUDB: "codenotary/immudb"
        DOCKER_IMAGE_IMMUADMIN: "codenotary/immuadmin"
        DOCKER_IMAGE_IMMUCLIENT: "codenotary/immuclient"
      steps:
        - run: |
            if [[ "${GITHUB_REF}" =~ refs/tags/v([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
              VERSION_TAG="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}.${BASH_REMATCH[3]}"
              VERSION_TAG_SHORT="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}"
            fi

            echo docker build --tag "${DOCKER_IMAGE_IMMUDB}:dev" -f Dockerfile .
            echo docker build --tag "${DOCKER_IMAGE_IMMUADMIN}:dev" -f Dockerfile.immuadmin .
            echo docker build --tag "${DOCKER_IMAGE_IMMUCLIENT}:dev" -f Dockerfile.immuclient .

            echo docker login ...
            
            echo docker push "${DOCKER_IMAGE_IMMUDB}:dev"
            echo docker push "${DOCKER_IMAGE_IMMUADMIN}:dev"
            echo docker push "${DOCKER_IMAGE_IMMUCLIENT}:dev"

            if [[ ! -z "$VERSION_TAG" ]]; then
              for tag in "${VERSION_TAG}" "${VERSION_TAG_SHORT}" "latest"; do
                echo docker tag "${DOCKER_IMAGE_IMMUDB}:dev" "${DOCKER_IMAGE_IMMUDB}:${tag}"
                echo docker push "${DOCKER_IMAGE_IMMUDB}:${tag}"

                echo docker tag "${DOCKER_IMAGE_IMMUADMIN}:dev" "${DOCKER_IMAGE_IMMUADMIN}:${tag}"
                echo docker push "${DOCKER_IMAGE_IMMUADMIN}:${tag}"

                echo docker tag "${DOCKER_IMAGE_IMMUCLIENT}:dev" "${DOCKER_IMAGE_IMMUCLIENT}:${tag}"
                echo docker push "${DOCKER_IMAGE_IMMUCLIENT}:${tag}"
              done
            fi

            
